version: 2

jobs:
  build:
    docker:
      - image: circleci/16.04-scm-dind
    steps:
      - checkout
      - run: git submodule sync
      - update
      - run: sudo apt-get update
      - install
      - run: build/depends/install
      - build
      - run: build/gcc/make
      - test
      - run cd test ; ../exe/gamecake.x64 lua/unit.lua
