version: 2
jobs:
  build:
    docker:
      - image: xriss/gamecake
    steps:
      - checkout
      - run:
          name: sync git
          command: git submodule sync
      - run:
          name: make x64
          command: build/make --clean
      - run:
          name: make exe
          command: build/make --clean --gcc=mingw
      - run:
          name: test
          command: cd test ; ../exe/gamecake.x64 lua/unit.lua
      - store_artifacts:
          path: exe/gamecake.x64
          path: exe/gamecake.exe
