name: gamecake
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: a single exe cross platform game engine # 79 char long summary
description: |
  GameCake is a single exe cross platform game engine,
  it is simply Lua built with embedded bindings to many libraries.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  build-gamecake:
    plugin: autotools
    source: .
